version: "3"
services:
  node:
    image: node:17-alpine
    restart: "no"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "34200:4200"
    command:
      [
        "/bin/sh",
        "-c",
        "npm install && ./node_modules/.bin/ng serve --host 0.0.0.0",
      ]

  openJdk:
    image: maven:3.8-openjdk-11
    restart: "no"
    ports:
      - "38080:38080"
    working_dir: /usr/src/rps
    volumes:
      - ./backend:/usr/src/rps
    command:
      [
        "/bin/sh",
        "-c",
        "mvn install -DskipTests && mvn exec:java -Dexec.mainClass='com.rps.rpsbackend.RpsBackendApplication'",
      ]
